### ISSUE TITLE
Failed to load parent block root: execution reverted

### ISSUE THREAD

**Issue by asanson1404** [Layr-Labs/eigenpod-proofs-generation#103]
Hey there,

I'm currently trying to generate a Validator Proof for my Eigen Pod. I'm using my Alchemy endpoint for `$NODE_ETH` and a public beacon RPC url for  `$NODE_BEACON` (https://ethereum-holesky-beacon-api.publicnode.com).

Below is the command I ran:
```shell
$ ./cli --beaconNode $NODE_BEACON --podAddress $EIGENPOD_ADDRESS --execNode $NODE_ETH --owner $EIGENPOD_PK credentials
```

Here is my output:
```shell
{"level":"info","time":"2024-07-25T18:35:46+08:00","message":"Connected to Standard (HTTP)\n"}
error: Failed to generate validator proof

caused by: failed to load parent block root: execution reverted
```

Do you have any idea of what causes that error?

**Comment by wadealexc** [comment]
Could you provide your pod address please?

**Comment by asanson1404** [comment]
My pod addr:
0xab93E8bC5f7A2c22D9Dcae4943095a5709F6E2fC

**Comment by wadealexc** [comment]
This pod is not using our new holesky-preprod deployment, it's using our public testnet deployment, which is roughly equivalent to our current mainnet code.

The CLI you're using does not support this version of EigenPods. You will want to use the proofgen repo's last release for this -- https://github.com/Layr-Labs/eigenpod-proofs-generation/releases/tag/v0.0.14-stable

If you're trying to test the new EigenPod redesign shipping soon (which is what the CLI you're using supports), you need to use our holesky-preprod deployment to create a new EigenPod. Details for that can be found here: https://hackmd.io/kZp6wiC8S-aIwStA0-XyMw
