### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *core.TracerCallbacks

### ISSUE THREAD

**Issue by asanson1404** [Layr-Labs/eigenpod-proofs-generation#110]
Hey,

I'm trying to generate a Checkpoint Proof for that Eigen Pod: 0xe78d849E46CF8e616ffab6Dc2B027E8C56BF8498

To do so, I'm using the last version of the CLI and I run the following command:
```shell
$ ./cli checkpoint -s $EIGENPOD_PK -p $EIGENPOD_ADDRESS -b $NODE_BEACON -e $NODE_ETH --force
``` 
Unfortunately, the execution panics...
![image](https://github.com/user-attachments/assets/114796cd-c104-41fb-a31b-486c53d8b8af)

Can you help @wadealexc?

**Comment by wadealexc** [comment]
Guessing this is fixed here: https://github.com/Layr-Labs/eigenpod-proofs-generation/pull/116
