### ISSUE TITLE
Building is not working

### ISSUE THREAD

**Issue by gurujustin** [Layr-Labs/eigenpod-proofs-generation#40]
I followed instruction on Read.me.
I run 'go build' in generation folder but there is not any action. I expected excutable binary file is generated but anything is created.
After then, if I run this command
./generation/generation \
  -command ValidatorFieldsProof \
  -oracleBlockHeaderFile "./data/deneb_goerli_block_header_7431952.json" \
  -stateFile "./data/deneb_goerli_slot_7431952.json" \
  -validatorIndex 302913 \
  -outputFile "withdrawal_credential_proof_302913.json" \
  -chainID 5
I get this error : bash: ./generation/generation: cannot execute binary file: Exec format error

What is the problem?

**Comment by ruXlab** [comment]
I've got the same issue, for some reason it builds the binary for the different arch:

```
$ file ./generation
./generation: Mach-O 64-bit arm64 executale.
```

Despite using compiler on Linux amd64 arch with the default settings

**Comment by ruXlab** [comment]
The issue has been resolved. Don't forget to remove the macos executable `generation` file that's part of the repository to avoid confusion
