### ISSUE TITLE
How to generate Credential and Checkpoint Proofs without having a ETH node?

### ISSUE THREAD

**Issue by asanson1404** [Layr-Labs/eigenpod-proofs-generation#97]
Hello,

I would like to generate the Credential Proofs and Checkpoint Proofs for my Eigen Pod.

I think the only way to have such proofs is by using your CLI but, unfortunately, I'm not able to provide the urls of an execution and a beacon ETH node...
So I'm not in position to run the following command:
```shell
$ ./cli --beaconNode $NODE_BEACON --podAddress $EIGENPOD_ADDRESS --execNode $NODE_ETH --owner $EIGENPOD_PK credentials
```

Is there a way to get the proofs by using a beacon chain public api such as https://beaconcha.in/api/v1/slot/1?apikey=<your_key>?
In that case, what would be the correct endpoints?

Thanks for your answer!

**Comment by wadealexc** [comment]
You can pass in public ETH and beacon chain APIs via the `--beaconNode` and `--execNode` flags. You do not need to run a node yourself.
